/*
 * AUTOGENERATED - DON'T EDIT
 * Your edits in this file will be overwritten in the next build!
 * Modify the docusaurus.config.js file at your site's root instead.
 */
export default {
  "title": "Snow Beta Docs",
  "tagline": "Documentation to help you configure and use Snow Software products",
  "url": "https://docs-app.dev-snowsoftware.io",
  "baseUrl": "/",
  "onBrokenLinks": "throw",
  "onBrokenMarkdownLinks": "warn",
  "favicon": "img/favicon.ico",
  "organizationName": "Snow Software",
  "projectName": "docusaurus",
  "i18n": {
    "defaultLocale": "en",
    "locales": [
      "en"
    ],
    "localeConfigs": {
      "en": {
        "htmlLang": "en-us",
        "direction": "ltr"
      }
    },
    "path": "i18n"
  },
  "noIndex": true,
  "presets": [
    [
      "classic",
      {
        "docs": {
          "sidebarPath": "/Users/scottbulloch/repositories/StaticWebappRoot/sidebars.js",
          "routeBasePath": "/"
        },
        "blog": {
          "showReadingTime": true
        },
        "theme": {
          "customCss": "/Users/scottbulloch/repositories/StaticWebappRoot/src/css/custom.css"
        }
      }
    ],
    [
      "redocusaurus",
      {
        "debug": false,
        "config": "redocly.yaml",
        "specs": [
          {
            "id": "sam_api_computers",
            "spec": "docs/snow-atlas-api/sam-core-apis/computers-spec-beta.json",
            "route": "docs/snow-atlas-api/sam/computers"
          },
          {
            "id": "sam_api_licenses",
            "spec": "docs/snow-atlas-api/sam-core-apis/Licenses_v160.json",
            "route": "docs/snow-atlas-api/sam/licenses"
          },
          {
            "id": "sam_api_useraccounts",
            "spec": "docs/snow-atlas-api/sam-core-apis/sam_users.yaml",
            "route": "docs/snow-atlas-api/sam/users"
          },
          {
            "id": "sam_api_useraccounts_views",
            "spec": "docs/snow-atlas-api/sam-core-apis/sam_users_view.yaml",
            "route": "docs/snow-atlas-api/sam/users_view"
          },
          {
            "id": "sam_api_customfields",
            "spec": "https://westeurope.snowsoftware.io/api/customfields/meta/http",
            "route": "docs/snow-atlas-api/sam/customfields"
          }
        ],
        "theme": {
          "primaryColor": "#1890ff"
        }
      }
    ]
  ],
  "themes": [
    [
      "/Users/scottbulloch/repositories/StaticWebappRoot/node_modules/@easyops-cn/docusaurus-search-local/dist/server/server/index.js",
      {
        "docsRouteBasePath": "/",
        "hashed": true
      }
    ]
  ],
  "themeConfig": {
    "announcementBar": {
      "id": "Site_Notice",
      "content": "This site is Temporary! Please use the following link for GA API documentation: <a target=\"_blank\" rel=\"noopener noreferrer\" href=\"https://docs.snowsoftware.io/snow-atlas-api/resources/\"> https://docs.snowsoftware.io/snow-atlas-api/resources/ </a>.",
      "backgroundColor": "#20232a",
      "textColor": "#fff",
      "isCloseable": false
    },
    "navbar": {
      "title": "Snow Atlas API Beta Docs",
      "logo": {
        "alt": "Snow Beta Docs Home",
        "src": "img/logo.svg"
      },
      "items": [
        {
          "type": "dropdown",
          "label": "More resources",
          "position": "left",
          "items": [
            {
              "href": "https://docs.snowsoftware.com/",
              "label": "Documentation"
            },
            {
              "href": "https://community.snowsoftware.com/s/",
              "label": "Community"
            }
          ]
        },
        {
          "type": "search",
          "position": "right"
        }
      ],
      "hideOnScroll": false
    },
    "footer": {
      "style": "dark",
      "links": [
        {
          "label": "Terms of use",
          "href": "https://www.snowsoftware.com/legal/termsofuse"
        },
        {
          "label": "Privacy policy",
          "href": "https://www.snowsoftware.com/seo/legal-privacy-policy"
        },
        {
          "label": "Data protection",
          "href": "https://www.snowsoftware.com/legal/dataprotection"
        },
        {
          "label": "Subscription center",
          "href": "https://go.snowsoftware.com/subscription-center.html"
        },
        {
          "label": "Community",
          "href": "https://community.snowsoftware.com/s/"
        },
        {
          "label": "Docs Feedback",
          "href": "mailto:docsportal-feedback@snowsoftware.com"
        }
      ],
      "copyright": "Copyright © 2025 Snow Software"
    },
    "prism": {
      "theme": {
        "plain": {
          "color": "#393A34",
          "backgroundColor": "#f6f8fa"
        },
        "styles": [
          {
            "types": [
              "comment",
              "prolog",
              "doctype",
              "cdata"
            ],
            "style": {
              "color": "#999988",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "namespace"
            ],
            "style": {
              "opacity": 0.7
            }
          },
          {
            "types": [
              "string",
              "attr-value"
            ],
            "style": {
              "color": "#e3116c"
            }
          },
          {
            "types": [
              "punctuation",
              "operator"
            ],
            "style": {
              "color": "#393A34"
            }
          },
          {
            "types": [
              "entity",
              "url",
              "symbol",
              "number",
              "boolean",
              "variable",
              "constant",
              "property",
              "regex",
              "inserted"
            ],
            "style": {
              "color": "#36acaa"
            }
          },
          {
            "types": [
              "atrule",
              "keyword",
              "attr-name",
              "selector"
            ],
            "style": {
              "color": "#00a4db"
            }
          },
          {
            "types": [
              "function",
              "deleted",
              "tag"
            ],
            "style": {
              "color": "#d73a49"
            }
          },
          {
            "types": [
              "function-variable"
            ],
            "style": {
              "color": "#6f42c1"
            }
          },
          {
            "types": [
              "tag",
              "selector",
              "keyword"
            ],
            "style": {
              "color": "#00009f"
            }
          }
        ]
      },
      "darkTheme": {
        "plain": {
          "color": "#F8F8F2",
          "backgroundColor": "#282A36"
        },
        "styles": [
          {
            "types": [
              "prolog",
              "constant",
              "builtin"
            ],
            "style": {
              "color": "rgb(189, 147, 249)"
            }
          },
          {
            "types": [
              "inserted",
              "function"
            ],
            "style": {
              "color": "rgb(80, 250, 123)"
            }
          },
          {
            "types": [
              "deleted"
            ],
            "style": {
              "color": "rgb(255, 85, 85)"
            }
          },
          {
            "types": [
              "changed"
            ],
            "style": {
              "color": "rgb(255, 184, 108)"
            }
          },
          {
            "types": [
              "punctuation",
              "symbol"
            ],
            "style": {
              "color": "rgb(248, 248, 242)"
            }
          },
          {
            "types": [
              "string",
              "char",
              "tag",
              "selector"
            ],
            "style": {
              "color": "rgb(255, 121, 198)"
            }
          },
          {
            "types": [
              "keyword",
              "variable"
            ],
            "style": {
              "color": "rgb(189, 147, 249)",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "comment"
            ],
            "style": {
              "color": "rgb(98, 114, 164)"
            }
          },
          {
            "types": [
              "attr-name"
            ],
            "style": {
              "color": "rgb(241, 250, 140)"
            }
          }
        ]
      },
      "additionalLanguages": [],
      "magicComments": [
        {
          "className": "theme-code-block-highlighted-line",
          "line": "highlight-next-line",
          "block": {
            "start": "highlight-start",
            "end": "highlight-end"
          }
        }
      ]
    },
    "docs": {
      "sidebar": {
        "hideable": true,
        "autoCollapseCategories": true
      },
      "versionPersistence": "localStorage"
    },
    "colorMode": {
      "defaultMode": "light",
      "disableSwitch": false,
      "respectPrefersColorScheme": false
    },
    "metadata": [],
    "tableOfContents": {
      "minHeadingLevel": 2,
      "maxHeadingLevel": 3
    }
  },
  "baseUrlIssueBanner": true,
  "onDuplicateRoutes": "warn",
  "staticDirectories": [
    "static"
  ],
  "customFields": {},
  "plugins": [],
  "scripts": [],
  "headTags": [],
  "stylesheets": [],
  "clientModules": [],
  "titleDelimiter": "|",
  "markdown": {
    "mermaid": false
  }
};
