name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          lfs: false
            #Checkout the directory of the remote Repo
            
      - uses : actions/checkout@v4
        with :
          ref: main
          repository: 'Scottbulloch/StaticWebappOne'
          sparse-checkout: 'docs/Commander/*'
          path: 'checkout_commander'
          sparse-checkout-cone-mode: false
          #ssh-key: ${{ secrets.SSH_READ_ALL }}. Uncomment for Snow Global Read all for go live to read from another Repo in Snow GH

      - name: Move Commander to Docs
        # This step is needed because expo-github-action does not support paths.
        # Therefore Commander should be moved to the docs folder.
        run: |
          echo 'print current directory'
          pwd
          ls -lah
          echo 'print checout_commander contents'
          cd checkout_commander
          pwd
          tree
          echo 'docs/Commander before move'
          cd /home/runner/work/StaticWebappRoot/StaticWebappRoot/docs/Commander/
          tree 
          echo 'relocate Contents from commander docs checkout to Correct folder in current deploy'
          mv -f /home/runner/work/StaticWebappRoot/StaticWebappRoot/checkout_commander/docs/Commander/* /home/runner/work/StaticWebappRoot/StaticWebappRoot/docs/Commander/ -v
          rm -rf /home/runner/work/StaticWebappRoot/StaticWebappRoot/checkout_commander
          echo 'docs/Commander dir after move'
          cd /home/runner/work/StaticWebappRoot/StaticWebappRoot/docs/Commander/
          tree 
          echo 'move Commander contents to /docs/Comamnder.  Complete!!!'     
          
      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_GREEN_WATER_0897E8710 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: "upload"
          ###### Repository/Build Configurations - These values can be configured to match your app requirements. ######
          # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
          app_location: "/" # App source code path
          api_location: "" # Api source code path - optional
          output_location: "build" # Built app content directory - optional
          ###### End of Repository/Build Configurations ######

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_GREEN_WATER_0897E8710 }}
          action: "close"
