# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - bulletwebapp

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
    
  copydocs:
    name: Unused Placeholder
    runs-on: ubuntu-latest
    steps:
      - name: Not running stuff here
        run: |
          echo 'Unused Placeholder'
          
  build:
    runs-on: ubuntu-latest
    needs: copydocs
    steps:
      #Checkout main of the current repo
      - uses : actions/checkout@v4
        with :
          ref: main
          
      #Checkout the directory of the remote Repo
      - uses : actions/checkout@v4
        with :
          ref: main
          repository: 'Scottbulloch/StaticWebappOne'
          path: 'checkout_commander'
          sparse-checkout: 'docs/Commander/*'
          sparse-checkout-cone-mode: false
          #ssh-key: ${{ secrets.SSH_READ_ALL }}.   Snow Global Read all for go live

      - name: Move Commander to Docs
        # This step is needed because expo-github-action does not support paths.
        # Therefore Commander should be moved to the docs folder.
        run: |
          echo 'print current directory'
          pwd
          ls -lah

          echo 'print checout_commander contents'
          cd checkout_commander
          pwd
          tree

          echo 'docs/Commander before move'
          cd /home/runner/work/StaticWebappRoot/StaticWebappRoot/docs/Commander/
          tree 

          echo 'relocate Contents from commander docs checkout to Correct folder in current deploy'
          mv -f /home/runner/work/StaticWebappRoot/StaticWebappRoot/checkout_commander/docs/Commander/* /home/runner/work/StaticWebappRoot/StaticWebappRoot/docs/Commander/ -v
          rm -rf /home/runner/work/StaticWebappRoot/StaticWebappRoot/checkout_commander

          echo 'docs/Commander dir after move'
          cd /home/runner/work/StaticWebappRoot/StaticWebappRoot/docs/Commander/
          tree 
          echo 'move Commander contents to /docs/Comamnder.  Complete!!!'  
      
      - name: Set up Node.js version
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: npm install, build, and test
        run: |
          npm install
          npm run build --if-present
          npm run test --if-present
          
      - name: Zip artifact for deployment
        run: |
          cd /home/runner/work/StaticWebappRoot/StaticWebappRoot/
          zip -r release.zip .
        #run: zip release.zip ./* -r
        
      - name: Check Current Directory
        run: |
          echo 'list current directory'
          pwd
          ls -lah
          
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: /home/runner/work/StaticWebappRoot/StaticWebappRoot/release.zip
          
  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Unzip artifact for deployment
        run: unzip release.zip
      
      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'bulletwebapp'
          slot-name: 'Production'
          package: .
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_739D6658DADF44F69B7D4D0B6AFFA24F }}
